version: "3.7"

services:
  postgres:
    image: postgres:14
    container_name: MovieMoodBot
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: BotData
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
